Footer Component
Jima-J9M1/Eduvi-E-learning pull request #28
Opened 2023-08-25 14:58 UTC by inasw

This pull request introduces a new component called Footer. It provides a footer section for the website, displaying relevant information and links.

2023-08-25 18:38 UTC, MohammedIbrahim8887 commented
Please sendyout PR to developement

2023-08-27 11:13 UTC, MohammedIbrahim8887 requested changes

2023-08-27 11:13 UTC, MohammedIbrahim8887 commented on src/App.tsx
only add provider wrappers in App.tsx please do move your component to the home page

2023-08-27 11:13 UTC, MohammedIbrahim8887 commented on src/Components/Common/Footer.tsx
since we are using react router to change our components please use the Link component for linking from one component to another such as privacy and policy,  provision

2023-08-27 11:13 UTC, MohammedIbrahim8887 commented on src/Components/Common/SubscriptionBox.tsx
since this is a form please treat it as a form and use react-hook-form to implement the form logic. You don't need e.preventDefault()

2023-08-27 18:06 UTC, Jima-J9M1 commented
Use App.tsx only for configuration, wrap provider  and App.tsx is a root node which is used for to pass global values to children.
Use footer component in Home.tsx instead of App.tsx.

2023-08-28 11:40 UTC, MohammedIbrahim8887 approved these changes
approved but please make changes on next PR

2023-08-28 11:42 UTC, merged